require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DiagramsController do

  def mock_diagram(stubs={})
    @mock_diagram ||= mock_model(Diagram, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all diagrams as @diagrams" do
      Diagram.stub(:all) { [mock_diagram] }
      get :index
      assigns(:diagrams).should eq([mock_diagram])
    end
  end

  describe "GET show" do
    it "assigns the requested diagram as @diagram" do
      Diagram.stub(:find).with("37") { mock_diagram }
      get :show, :id => "37"
      assigns(:diagram).should be(mock_diagram)
    end
  end

  describe "GET new" do
    it "assigns a new diagram as @diagram" do
      Diagram.stub(:new) { mock_diagram }
      get :new
      assigns(:diagram).should be(mock_diagram)
    end
  end

  describe "GET edit" do
    it "assigns the requested diagram as @diagram" do
      Diagram.stub(:find).with("37") { mock_diagram }
      get :edit, :id => "37"
      assigns(:diagram).should be(mock_diagram)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created diagram as @diagram" do
        Diagram.stub(:new).with({'these' => 'params'}) { mock_diagram(:save => true) }
        post :create, :diagram => {'these' => 'params'}
        assigns(:diagram).should be(mock_diagram)
      end

      it "redirects to the created diagram" do
        Diagram.stub(:new) { mock_diagram(:save => true) }
        post :create, :diagram => {}
        response.should redirect_to(diagram_url(mock_diagram))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diagram as @diagram" do
        Diagram.stub(:new).with({'these' => 'params'}) { mock_diagram(:save => false) }
        post :create, :diagram => {'these' => 'params'}
        assigns(:diagram).should be(mock_diagram)
      end

      it "re-renders the 'new' template" do
        Diagram.stub(:new) { mock_diagram(:save => false) }
        post :create, :diagram => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diagram" do
        Diagram.stub(:find).with("37") { mock_diagram }
        mock_diagram.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :diagram => {'these' => 'params'}
      end

      it "assigns the requested diagram as @diagram" do
        Diagram.stub(:find) { mock_diagram(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:diagram).should be(mock_diagram)
      end

      it "redirects to the diagram" do
        Diagram.stub(:find) { mock_diagram(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(diagram_url(mock_diagram))
      end
    end

    describe "with invalid params" do
      it "assigns the diagram as @diagram" do
        Diagram.stub(:find) { mock_diagram(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:diagram).should be(mock_diagram)
      end

      it "re-renders the 'edit' template" do
        Diagram.stub(:find) { mock_diagram(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diagram" do
      Diagram.stub(:find).with("37") { mock_diagram }
      mock_diagram.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the diagrams list" do
      Diagram.stub(:find) { mock_diagram }
      delete :destroy, :id => "1"
      response.should redirect_to(diagrams_url)
    end
  end

end
